services:
  composer:
    image: composer:2
    container_name: fee_composer
    volumes:
      - .:/app
    working_dir: /app
    command: ["install"]

  php:
    image: php:8.3-cli
    container_name: fee_calculator_php
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["php"]
    command: ["calculate-fee.php"]