services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fee_calculator_php
    command: php calculate-fee.php

  composer:
    image: composer:2
    container_name: fee_composer
    command: install
